imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:            ~
    translator:      ~
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  %locale%
    trust_proxy_headers: false # Whether or not the Request object should trust proxy headers (X_FORWARDED_FOR/HTTP_CLIENT_IP)
    session:         ~


# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles: [TerrificComposition,HWIOAuthBundle]
    # java: /usr/bin/java
    filters:
        less:
          node: /usr/local/bin/node
          node_paths: [/usr/local/lib/node, /usr/local/lib/node_modules]
          apply_to: "\.less$"
        cssrewrite: ~
        terrificrewrite:
            resource: %kernel.root_dir%/../vendor/brunschgi/terrific-core-bundle/Terrific/CoreBundle/Resources/config/terrificrewrite.xml
        # lessphp:
        #     apply_to: "\.less$"
        #     file:   %kernel.root_dir%/../vendor/leafo/lessphp/lessc.inc.php
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

hwi_oauth:
    # name of the firewall in which this bundle is active, this setting MUST be set
    firewall_name: main

    resource_owners:
        github:
            type:                github
            client_id:           bc85682621c0a4e346c9
            client_secret:       82f39a60808b94bf1c04207866198a8b184575bd
            scope:               ""
        twitter:
            type:                twitter
            client_id:           Gy7wIuajjHGpgTJxdbB1eg
            client_secret:       ivpsmlkmpUOqWtGYtpiSO2uvO6l7cm4O9xKM2EbzcI

    http_client:
        timeout:       10 # Time in seconds, after library will shutdown request, by default: 5
        verify_peer:   true # Setting allowing you to turn off SSL verification, by default: true
        ignore_errors: true # Setting allowing you to easier debug request errors, by default: true
        max_redirects: 5 # Number of HTTP redirection request after which library will shutdown request, by default: 5


terrific_composer:
    composition_bundles: [@TerrificComposition] # the bundles where the controllers for your frontend lie
    module_layout: @TerrificComposition::basemodule.html.twig # the layout to take for the separate module view