parameters:
    database_driver   : pdo_mysql
    database_host     : 127.0.0.1
    database_port     : 3306
    database_name     : terrific_io
    database_user     : terrific_io
    database_password : terrific_io

    mailer_transport  : smtp
    mailer_host       : localhost
    mailer_user       : ~
    mailer_password   : ~

    locale            : en
    secret            : ThisTokenIsNotSoSecretChangeIt
