jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    providers:
        fos_userbundle:
            id: fos_user.user_manager

    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            logout:       true
            anonymous:    true
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                login_path: /auth
                check_path: /auth/form-check

            oauth:
                resource_owners:
                    twitter: "/auth/check-twitter"
                    github: "/auth/check-github"
                login_path:        /auth
                failure_path:      /auth
                default_target_path: /profile

                # FOSUB integration
                oauth_user_provider:
                    service: hwi_oauth.user.provider.fosub_bridge

    access_control:
        - { path: ^/auth$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN
