jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    providers:
       oauth:
          id: "terrific_composition.user.provider"

    encoders:
        Terrific\Composition\Entity\User: plaintext

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            logout:       true
            anonymous:    true
            oauth:
                resource_owners:
                    twitter: "/auth/check-twitter"
                    github: "/auth/check-github"
                login_path:        /auth
                failure_path:      /auth
                default_target_path: /project/list

                oauth_user_provider:
                    service: terrific_composition.user.provider


    access_control:
        - { path: ^/auth, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/connect, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, role: ROLE_USER }

    role_hierarchy:
        ROLE_ADMIN:  ROLE_USER
