<?php

namespace Terrific\Composition\Entity;

use Doctrine\ORM\EntityRepository;
use Terrific\Composition\Entity\Snippet;
use Terrific\Composition\Entity\Module;

/**
 * ModuleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModuleRepository extends EntityRepository
{
    public function create() {
        $em = $this->getEntityManager();

        $module = new Module();
        $module->setTitle('My new experiment');
        $module->setDescription('Psst… please give away a secret about your experiment');

        $markup = new Snippet();
        $markup->setMode('text/html');
        $markup->setCode('<div class="mod mod-draft">Test</div>');

        $style = new Snippet();
        $style->setMode('text/css');
        $style->setCode('.mod-draft { color: navy }');

        $script = new Snippet();
        $script->setMode('text/javascript');
        $script->setCode('');

        $module->setMarkup($markup);
        $module->setStyle($style);
        $module->setScript($script);

        $em->persist($markup);
        $em->persist($style);
        $em->persist($script);

        $em->persist($module);
        $em->flush();

        return $module;
    }

    public function update($id, $tmpModule) {
        $em = $this->getEntityManager();

        $module = $this->find($id);

        $module->setCode($tmpModule->setTitle($tmpModule->getTitle()));
        $module->setCode($tmpModule->setDescription($tmpModule->getDescription()));
        $module->setCode($tmpModule->setMarkup($tmpModule->getMarkup()));
        $module->setCode($tmpModule->setStyle($tmpModule->getStyle()));
        $module->setCode($tmpModule->setScript($tmpModule->getScript()));

        $em->flush();

        return $module;
    }

    public function delete($id) {
        $em = $this->getEntityManager();

        $module = $this->find($id);

        $em->remove($module);
        $em->flush();
    }
}