<?php

namespace Terrific\Composition\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends EntityRepository
{

    public function getAll($user) {
        $em = $this->getEntityManager();

        $query = $em->createQuery('SELECT p FROM TerrificComposition:Project p WHERE p.user = :user')
            ->setParameter('user', $user);

        return $query->getResult();
    }

    public function get($user, $id)
    {
        $em = $this->getEntityManager();

        $query = $em->createQuery('SELECT p FROM TerrificComposition:Project p WHERE p.id = :id AND p.user = :user')
            ->setParameter('id', $id)
            ->setParameter('user', $user)
            ->setMaxResults(1);

        $result = $query->getResult();
        return $result[0];
    }

    public function create($user, $project) {
        $em = $this->getEntityManager();

        // create some default values
        $project->setUser($user);
        $project->setName('Lab');

        // persist it
        $em->persist($project);
        $em->flush();

        return $project;
    }

    public function update($id, $tmpProject) {
        $em = $this->getEntityManager();

        $project = $this->findOneById($id);
        $em->flush();

        return $project;
    }

    public function delete($id) {
        $em = $this->getEntityManager();

        $project = $this->findOneById($id);

        $em->remove($project);
        $em->flush();
    }
}
