<?php

namespace Terrific\Composition\Entity;

use Doctrine\ORM\EntityRepository;
use Terrific\Composition\Entity\Snippet;

/**
 * SnippetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SnippetRepository extends EntityRepository
{
    public function update($user, $id, $tmpSnippet) {
        $em = $this->getEntityManager();

        // check if the snippet belongs to the current user
        $this->checkByUserAndId($user, $id);

        $snippet = $this->findOneById($id);

        $snippet->setCode($tmpSnippet->getCode());
        $snippet->setMode($tmpSnippet->getMode());

        $em->flush();

        return $snippet;
    }

    private function checkByUserAndId($user, $id) {
        $em = $this->getEntityManager();

        $query = $em->createQuery('
            SELECT s
            FROM TerrificComposition:Project p, TerrificComposition:Module m, TerrificComposition:Snippet s
             WHERE m.project = p.id
                AND s.id = :id
                AND s.id = m.markup
                 OR s.id = m.style
                 OR s.id = m.script
                AND p.user = :user')
            ->setParameter('id', $id)
            ->setParameter('user', $user)
            ->setMaxResults(1);

        $result = $query->getResult();
        $snippet = $result[0];

        if(!$snippet) {
            throw new \Exception('the project with the id "'.$id.'" does not belong to you');
        }

        return $snippet;
    }
}