<?php

namespace Terrific\Composition\Entity;

use Doctrine\ORM\EntityRepository;
use Terrific\Composition\Entity\Snippet;

/**
 * SnippetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SnippetRepository extends EntityRepository
{
    public function create() {
        $em = $this->getEntityManager();

        $snippet = new Snippet();

        $em->persist($snippet);
        $em->flush();

        return $snippet;
    }

    public function update($id, $tmpSnippet) {
        $em = $this->getEntityManager();

        $snippet = $this->find($id);

        $snippet->setCode($tmpSnippet->getCode());
        $snippet->setMode($tmpSnippet->getMode());

        $em->flush();

        return $snippet;
    }

    public function delete($id) {
        $em = $this->getEntityManager();

        $snippet = $this->findOneById($id);

        $em->remove($snippet);
        $em->flush();
    }


}